### ISSUE TITLE
AttributeError: 'list' object has no attribute 'unsqueeze'

### ISSUE THREAD

**Issue by LiuFengHuiXueYYY** [acids-ircam/wavae#2]
Hello, may I ask what the problem is
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    train_step_melgan(model, opt, batch, writer, ROOT, step, device)
  File "F:\wavae-master\wavae-master\src\train_utils.py", line 13, in train_step_melgan
    data = data.unsqueeze(1).to(device)
AttributeError: 'list' object has no attribute 'unsqueeze'

**Comment by LiuFengHuiXueYYY** [comment]
data = data.unsqueeze(1).to(device)  
This is not correct. Should I write data[0].unsqueeze(1).to(device)  ?
